'use client';

import { useEffect, useRef, useState } from 'react';

const ArrowRight = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>;
const ArrowUpRight = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M7 17 17 7"/><path d="M7 7h10v10"/></svg>;
const Globe = ({s=24}:{s?:number}) => <svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><path d="M2 12h20"/><path d="M12 2a15.3 15.3 0 0 1 0 20"/><path d="M12 2a15.3 15.3 0 0 0 0 20"/></svg>;
const Twitter = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M22 5.8c-.7.3-1.5.5-2.3.6.8-.5 1.4-1.2 1.7-2.1-.8.5-1.6.8-2.5 1-1.5-1.6-4.3-1.5-5.7.4-.9 1.2-1 2.7-.4 4.1-3.2-.2-6.1-1.7-8.1-4.2-1.1 1.8-.5 4.1 1.3 5.2-.6 0-1.2-.2-1.7-.5 0 2 1.4 3.7 3.3 4.1-.6.2-1.2.2-1.8.1.5 1.7 2.1 2.9 3.9 2.9A8.5 8.5 0 0 1 3 19.5a12 12 0 0 0 6.5 1.9c7.8 0 12.3-6.7 12-12.8.8-.6 1.4-1.3 1.9-2.1z"/></svg>;
const Instagram = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="18" cy="6" r="1"/></svg>;

function useInView() { const ref=useRef<HTMLDivElement>(null); const [show,setShow]=useState(false); useEffect(()=>{const el=ref.current;if(!el) return; const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShow(true);io.disconnect();}},{rootMargin:'-100px'}); io.observe(el); return ()=>io.disconnect();},[]); return {ref,show}; }
function fadeVideo(element: HTMLVideoElement, to: number, duration = 500) { const start=performance.now();const from=parseFloat(element.style.opacity||'0')||0; const step=(n:number)=>{const p=Math.min((n-start)/duration,1); element.style.opacity=String(from+(to-from)*p); if(p<1) requestAnimationFrame(step);}; requestAnimationFrame(step);} 

export function HeroSection(){ const videoRef=useRef<HTMLVideoElement>(null); const fadingRef=useRef(false); useEffect(()=>{const v=videoRef.current;if(!v) return; const onCanPlay=()=>{v.play().catch(()=>undefined);v.style.opacity='0';fadeVideo(v,1,500);}; const onTime=()=>{if(fadingRef.current||!v.duration) return; if(v.duration-v.currentTime<=0.55){fadingRef.current=true; fadeVideo(v,0,500);}}; const onEnd=()=>{v.style.opacity='0'; setTimeout(()=>{v.currentTime=0;v.play().catch(()=>undefined);fadeVideo(v,1,500);fadingRef.current=false;},100);}; v.addEventListener('canplay',onCanPlay);v.addEventListener('timeupdate',onTime);v.addEventListener('ended',onEnd); return ()=>{v.removeEventListener('canplay',onCanPlay);v.removeEventListener('timeupdate',onTime);v.removeEventListener('ended',onEnd);};},[]);
return <section className="relative flex min-h-screen flex-col overflow-hidden bg-black"><video ref={videoRef} className="absolute inset-0 h-full w-full object-cover object-bottom" src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260405_074625_a81f018a-956b-43fb-9aee-4d1508e30e6a.mp4" muted autoPlay playsInline preload="auto" style={{opacity:0}}/><div className="relative z-20 px-6 py-6"><nav className="liquid-glass mx-auto flex max-w-5xl items-center justify-between rounded-full px-6 py-3"><div className="flex items-center gap-3 text-white"><Globe/><span className="text-lg font-semibold">DefTech Asme</span></div><div className="ml-8 hidden gap-8 text-sm font-medium text-white/80 md:flex"><a href="#about">Capabilities</a><a href="#innovation">Innovation</a><a href="#services">Programs</a></div><div className="flex items-center gap-2"><button className="text-sm text-white">Sign Up</button><button className="liquid-glass rounded-full px-6 py-2 text-sm text-white">Login</button></div></nav></div><div className="relative z-10 flex flex-1 -translate-y-[20%] flex-col items-center justify-center px-6 py-12 text-center"><h1 className="font-instrument whitespace-nowrap text-7xl tracking-tight text-white md:text-8xl lg:text-9xl">Know it then <em className="italic">all</em>.</h1><div className="liquid-glass mt-8 flex w-full max-w-xl items-center gap-3 rounded-full py-2 pl-6 pr-2"><input className="w-full bg-transparent text-white outline-none placeholder:text-white/40" placeholder="Enter your email"/><button className="rounded-full bg-white p-3 text-black"><ArrowRight/></button></div><p className="mt-6 px-4 text-sm leading-relaxed text-white">Stay ahead on defence tech signals, operational insights, and funding readiness updates.</p><button className="liquid-glass mt-6 rounded-full px-8 py-3 text-sm font-medium text-white hover:bg-white/5">Read Manifesto</button></div><div className="relative z-10 flex justify-center gap-4 pb-12">{[Instagram,Twitter,Globe].map((Icon,idx)=><button key={idx} className="liquid-glass rounded-full p-4 text-white/80 transition-all hover:bg-white/5 hover:text-white">{'s' in Icon?<Icon s={20}/>:<Icon/>}</button>)}</div></section> }

export function AboutSection(){const {ref,show}=useInView();return <section id="about" ref={ref} className="relative overflow-hidden bg-black px-6 pb-10 pt-32 md:pb-14 md:pt-44"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(255,255,255,0.03)_0%,_transparent_70%)]"/><div className="relative mx-auto max-w-6xl"><p className={`text-sm uppercase tracking-widest text-white/40 transition-all duration-700 ${show?'translate-y-0 opacity-100':'translate-y-5 opacity-0'}`}>About Us</p><h2 className={`mt-6 text-4xl leading-[1.1] tracking-tight text-white transition-all delay-100 duration-700 md:text-6xl lg:text-7xl ${show?'translate-y-0 opacity-100':'translate-y-10 opacity-0'}`}>Pioneering <span className="font-instrument italic text-white/60">defence ideas</span> for<br className="hidden md:block"/>minds that <span className="font-instrument italic text-white/60">create, build, and inspire.</span></h2></div></section>}

export function FeaturedVideoSection(){const {ref,show}=useInView();return <section className="overflow-hidden bg-black px-6 pb-20 pt-6 md:pb-32 md:pt-10"><div className="mx-auto max-w-6xl"><div ref={ref} className={`relative aspect-video overflow-hidden rounded-3xl transition-all duration-700 ${show?'translate-y-0 opacity-100':'translate-y-14 opacity-0'}`}><video className="h-full w-full object-cover" muted autoPlay loop playsInline preload="auto" src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260402_054547_9875cfc5-155a-4229-8ec8-b7ba7125cbf8.mp4"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-6 md:p-10"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div className="liquid-glass max-w-md rounded-2xl p-6 md:p-8"><p className="mb-3 text-xs uppercase tracking-widest text-white/50">Our Approach</p><p className="text-sm leading-relaxed text-white md:text-base">We believe every defence platform starts with mission-led curiosity. Each validation cycle opens the next path to resilient deployment.</p></div><button className="liquid-glass self-start rounded-full px-8 py-3 text-sm font-medium text-white transition-transform hover:scale-105 active:scale-95">Explore more</button></div></div></div></div></section>}

export function PhilosophySection(){const {ref,show}=useInView();return <section id="innovation" className="overflow-hidden bg-black px-6 py-28 md:py-40"><div className="mx-auto max-w-6xl"><h2 ref={ref} className={`mb-16 text-5xl tracking-tight text-white transition-all duration-700 md:mb-24 md:text-7xl lg:text-8xl ${show?'translate-y-0 opacity-100':'translate-y-10 opacity-0'}`}>Innovation <span className="font-instrument italic text-white/40">x</span> Vision</h2><div className="grid grid-cols-1 gap-8 md:grid-cols-2 md:gap-12"><div className={`aspect-[4/3] overflow-hidden rounded-3xl transition-all duration-700 ${show?'translate-x-0 opacity-100':'-translate-x-10 opacity-0'}`}><video className="h-full w-full object-cover" muted autoPlay loop playsInline preload="auto" src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260307_083826_e938b29f-a43a-41ec-a153-3d4730578ab8.mp4"/></div><div className={`space-y-8 transition-all duration-700 ${show?'translate-x-0 opacity-100':'translate-x-10 opacity-0'}`}><div><p className="mb-4 text-xs uppercase tracking-widest text-white/40">Choose your space</p><p className="text-base leading-relaxed text-white/70 md:text-lg">Every meaningful breakthrough begins where operational discipline intersects with creative engineering vision. We build exactly in that zone.</p></div><div className="h-px w-full bg-white/10"/><div><p className="mb-4 text-xs uppercase tracking-widest text-white/40">Shape the future</p><p className="text-base leading-relaxed text-white/70 md:text-lg">We align founders, field operators, and long-horizon capital so mission-critical innovation can scale with confidence.</p></div></div></div></div></section>}

export function ServicesSection(){const {ref,show}=useInView(); const cards=[['https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260314_131748_f2ca2a28-fed7-44c8-b9a9-bd9acdd5ec31.mp4','Strategy','Research & Insight','We analyze battlefield trends, procurement constraints, and adoption signals to identify durable defence opportunities.'],['https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260324_151826_c7218672-6e92-402c-9e45-f1e0f454bdc4.mp4','Craft','Design & Execution','From validation to deployment, we shape systems that are compliant, operable, and built for mission environments.']]; return <section id="services" className="relative overflow-hidden bg-black px-6 py-28 md:py-40"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_rgba(255,255,255,0.02)_0%,_transparent_60%)]"/><div className="relative mx-auto max-w-6xl"><div ref={ref} className={`mb-8 flex items-center justify-between transition-all duration-700 md:mb-10 ${show?'translate-y-0 opacity-100':'translate-y-8 opacity-0'}`}><h2 className="text-3xl tracking-tight text-white md:text-5xl">What we do</h2><p className="hidden text-sm text-white/40 md:block">Our services</p></div><div className="grid grid-cols-1 gap-6 md:grid-cols-2 md:gap-8">{cards.map(([src,tag,title,desc],i)=><article key={title} className={`liquid-glass group overflow-hidden rounded-3xl transition-all duration-700 ${show?'translate-y-0 opacity-100':'translate-y-12 opacity-0'}`} style={{transitionDelay:`${i*150}ms`}}><div className="relative aspect-video overflow-hidden"><video className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" muted autoPlay loop playsInline preload="auto" src={src}/><div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent"/></div><div className="p-6 md:p-8"><div className="mb-4 flex items-center justify-between"><p className="text-xs uppercase tracking-widest text-white/40">{tag}</p><span className="liquid-glass rounded-full p-2 text-white"><ArrowUpRight/></span></div><h3 className="mb-3 text-xl tracking-tight text-white md:text-2xl">{title}</h3><p className="text-sm leading-relaxed text-white/50">{desc}</p></div></article>)}</div></div></section>}
